export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";


export const SEND_VERIFICATION_CODE_REQUEST = "SEND_VERIFICATION_CODE_REQUEST";
export const SEND_VERIFICATION_CODE_SUCCESS = "SEND_VERIFICATION_CODE_SUCCESS";
export const SEND_VERIFICATION_CODE_FAIL = "SEND_VERIFICATION_CODE_FAIL";

export const VERIFY_VERIFICATION_CODE_REQUEST = "VERIFY_VERIFICATION_CODE_REQUEST"
export const VERIFY_VERIFICATION_CODE_SUCCESS = "VERIFY_VERIFICATION_CODE_SUCCESS"
export const VERIFY_VERIFICATION_CODE_FAIL = "VERIFY_VERIFICATION_CODE_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS";
